#!/bin/bash
# geneinspect

# Define the path to the Python script
PYTHON_SCRIPT="/etc/genome_inspector/Genome_Inspector.py"

# Check if the Python script exists and is executable
if [[ ! -f "$PYTHON_SCRIPT" ]]; then
    echo "Error: $PYTHON_SCRIPT not found!"
    exit 1
fi

if [[ ! -x "$PYTHON_SCRIPT" ]]; then
    echo "Error: $PYTHON_SCRIPT is not executable!"
    exit 1
fi

# Optionally, activate a virtual environment if needed
# source /path/to/venv/bin/activate

# Execute the Python script
python "$PYTHON_SCRIPT"
